<?php

namespace Upmc\SuiviStagiaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AvisPedagogiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisPedagogiqueRepository extends EntityRepository
{
}
