<?php

namespace Upmc\SuiviStagiaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntretienRepository extends EntityRepository
{
}
